# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a83dd5ac105a944a691cec0d75fb0d9113d5fd6e7bace08fe7a3986eee4ea98811b5b78e222e04ff5a34b9ea9c720fefbdf866186dc008a7fd2aa5523118b43

test:
  secret_key_base: 179f6cf2e999e4e73241c25bfbbed13ccf66730479a93c1f7e3d5203a212fe4ae5e5833d40ac2e2999f8c89c909c9e62d03646a3d5959d0759ab66a52b4e42ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
